#!/bin/bash

list_ping(){
# arguments : <start> <end> <subnet>
# output : ip address in seperate line
    for i in `seq ${1} ${2}`
    do
        ping -c1 192.168.${3}.${i} > /dev/null
	if [ $? -eq 0 ]; then
		echo "192.168.${3}.${i}"
	fi
    done
}

get_current_ip(){

}
